url: https://anotherstripclub.com
baseurl: /

# Site settings
title: The Strip Club
email: anotherstripclub@gmail.com
description: a late night fried chicken strips that will tease the tastebuds.


# Team names, titles and social links
people:
- name: Guy Persons
  pic: 1
  position: Vice President of Stripology
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #facebook.com/anotherstripclub

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/anotherstripclub
  - title: facebook
    url: http://facebook.com/anotherstripclub
  - title: instagram
    url: http://instagram.com/anotherstripclub
  - title: github
    url: http://github.com/anotherstripclub

# Postal address (add as many lines as necessary)
address:
  - line: 123 TBD st
  - line: Honolulu, HI 96826

# Build settings
markdown: kramdown
permalink: pretty
